export type TLoggedUser = {
  id?: string;
  uf?: string;
  cep?: string;
  cpf?: string;
  role?: string;
  plan?: string;
  city?: string;
  name?: string;
  email?: string;
  phone?: string;
  degree?: string;
  payday?: number;
  street?: string;
  tokenId?: string;
  modality?: string;
  district?: string;
  graduation?: string;
  organization?: string;
};
