version: '1'

services:
  app:
    build: 
      context: ../
      dockerfile: DockerFile
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: postgres://devteam:1f4320ef808441a2a0cbe754ff29783f@db:5432/bjj-database
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres
    environment:
      POSTGRES_DB: bjj-database
      POSTGRES_USER: devteam
      POSTGRES_PASSWORD: 1f4320ef808441a2a0cbe754ff29783f
    ports:
      - '5432:5432'
