name: Deploy to VPS

on:
  push:
    branches:
      - main  # ou o nome da branch que você usa

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to VPS
        run: |
          ssh user@your_vps_ip 'cd /path/to/your/project && git pull && npm install && npm run build'
